language: ruby
rvm: 2.4.1

git:
  depth: 6
  lfs_skip_smudge: true

cache:
  bundler: true
  directories:
  - node_modules/
  - lib/
  - vendor/bundle
  - tmp/
  - ".sass-cache"

before_install:
- nvm install 6.10.0

install:
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
- npm install -g bower gulp-cli
- npm install
- bower install
- curl https://s3-eu-west-1.amazonaws.com/wjdp-lib/htmltest > _bin/htmltest
- chmod +x _bin/htmltest
- _bin/htmltest --version

before_script:
- _bin/prep.sh

script:
- gulp build_deploy
- gulp test

after_success:
- _bin/deploy_ghp.sh
- _bin/deploy_netlify.sh
- bundle exec ruby _bin/github_tasks.rb

env:
  global:
  - secure: KEaPPezS8BSGFmCLKkHikaCxIibWIq3Pp6fXLwNc7avkvlgF9qsFVgMS2GsCL3c/Hj+xXjmwziXAl9VCP/s8+K1Q1epXKlqXz3HOXFnt9Y5rpaOtHgugq4e9KhmQrlQp52cnemVGvfQNbXxMw6D/cvaa2O++Dne+cvGcENLvCB8=
  - secure: NZXEvEfEjB+9Adgc4irbQWF6xYGIjvlAIkUYOzsK135sIbsK4xxjnAGfkEuaKv0LBaUeTh7jGJZKPE8IeStPkcbX6K4G6P3Q9joOCnwBF+hz43wheKpBmkv5wZSJ3+TEdo42D4E1/5D1cX2rzYY4QyWZ5FSzkO7B2RitZ+cEN0Q=
  - secure: TgCyjoUgVWTCGoUCO+vuxI+ZsWCfQqlSLbBciTjskD/PfN/2s3O0ahcDkJEw+Tpaok4I3wPOF8L+eydet9GSQnnz4nF+RS+UF6tu+CDnVQtZjN4l9xTxoSpHHLkALohftes08NxR1fumPC3Ip9/8nBcEHGgQRB+KDrHUqxtSjXk=
  - secure: hp4bb8UUlTfIq49EEuPdKUerFMIBevvYpcxQmm8eBHucPFR6z9MY1XRAz8NHeis8RMppawhIfu6SErip5eub2f2Ds/WEqId078+3d56oI517HS7PnP9ZrW2dfX18I5dbRd9onUdPHHdC5DdYR/mVZFi6YJrRs7+WeklGE8VrAzg=
  - secure: AXtiDdkQ/EMJEw37WGrF8rCcETvC4JswCJDrCTRH54Y/mGbs8kNJw/yX7bEzWCWLaX5eqLhyQzldh8k38EwPTcb1VKJS32SH2ce730+hbpgYuhAVwB2WwgVFdOlqXUd6eIeb6EVgcvIshFKdcjQ6ww4MunG79oG8E76tQGoJ+PM=
  - secure: PxTpXT3mGNU+uWE/OYaOyGMziJ/cJ0uPAfr73enUx7i+8SRYeLLFQxwZBcbHcD/7ZDpEZcYYFHTC3d3nX5OItmOhJqbtaB0cNHFq+VVj9yiZJLjw9L/FdDwWrwxOzccGdsGyDVEWv+v8jnu5EoP+lHYVmKSV8zt5aOe65AIXMYM=
  - secure: gD9bKWPench6Qbh5CDwNK2co6F1BJGGIZIP06MAZ3YJLZJR5n20XpPTofHVNb/kvW6LsCD4OWa+r2ZXVg+CrGgt82KZfpHuQ53j3wVpqbCBMTAcdLuRCVyADBsCW3xO4xPQCX3NuHWDQaAzmGr2SPE+uRa3mIpNP9cMhIP4PeDk=
  - secure: VZdHjHPQXsetFTCBCUSF4+yXWUBuRRVr0ZSflDAyuGuryNTbA2T8KQoxOJDMcQVNjeVFukIs8p8VkTWWSTLgSfEsSqtayYFy5hBvOceVAZVh/0UX+GjWEn9IUVDOr/wFVuZ4ArwyiXmHxGgj/uBXOEIYks3TQRUFNzhqL7035gw=
  - secure: EXnIK2L0fhWcPklzbhbqjsQ9vNpxWPtjZkCB3OY0Z2ZD/Nt2CWqoOSgESh3ngSDu2y19gNzLCoctk8JA7mv9MO5BsUa2nuUQJ2mXubY0XrXl0i3PpICKJAWj0TcOQS8INw5DYcH51Eg1wl0o1FHm/7aw0oFhjfOMbav+2i7tEps=

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  on_success: change
  on_failure: always
  on_pull_requests: false

before_deploy:
  - _bin/export_cache.sh

deploy:
  provider: s3
  access_key_id:
    secure: "hh/BcZ28K3y8gkHxp+meTi5f9hzT1n9G1d1zURIyzlyk0haNRZTyrgyfl7ptuhs4NKXih4awwi1ESuW9aYstfEDM9eq2HvRuwyxpjqBJuuDQvZsTCw3aRZbCfrCaFI/0CV8FSTiKD+/9Kxq26sd5d+sbRaOoYZR0frlKxnCfXZc="
  secret_access_key:
    secure: "Z9tCiOupbFv+XduGxN91r3burR0YCq4TuOuR/imLG8ScFroVS3iC1w2FM5WmPuum534tLwXyXZSi+g1wfsitOfq8lg41Lee8OpVOHBHl3c2KfGwK3vX44mOHix0PC5X/KNW4IR5A9kKESWgMEzR1BcBRCptQiEIwNxDFgZVyITE="
  bucket: "nthp"
  region: "eu-west-1"
  acl: public_read
  skip_cleanup: true
  local_dir: tmp/export
  on:
    branch: master
