language: ruby
cache:
  bundler: true
  directories:
    - _site/images/resized
    - node_modules/
    - lib/
    - _asset_bundler_cache/
    - vendor/bundle
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - npm install
  - bower install
script: _bin/build.sh
after_script:
 - _bin/test.sh
 - _bin/deploy.sh
branches:
  only:
  - master
rvm:
- 2.1.2
env:
  global:
  - secure: KEaPPezS8BSGFmCLKkHikaCxIibWIq3Pp6fXLwNc7avkvlgF9qsFVgMS2GsCL3c/Hj+xXjmwziXAl9VCP/s8+K1Q1epXKlqXz3HOXFnt9Y5rpaOtHgugq4e9KhmQrlQp52cnemVGvfQNbXxMw6D/cvaa2O++Dne+cvGcENLvCB8=
  - secure: NZXEvEfEjB+9Adgc4irbQWF6xYGIjvlAIkUYOzsK135sIbsK4xxjnAGfkEuaKv0LBaUeTh7jGJZKPE8IeStPkcbX6K4G6P3Q9joOCnwBF+hz43wheKpBmkv5wZSJ3+TEdo42D4E1/5D1cX2rzYY4QyWZ5FSzkO7B2RitZ+cEN0Q=
  - secure: "TgCyjoUgVWTCGoUCO+vuxI+ZsWCfQqlSLbBciTjskD/PfN/2s3O0ahcDkJEw+Tpaok4I3wPOF8L+eydet9GSQnnz4nF+RS+UF6tu+CDnVQtZjN4l9xTxoSpHHLkALohftes08NxR1fumPC3Ip9/8nBcEHGgQRB+KDrHUqxtSjXk="
